name: Build SunamoStringSubstring

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    name: Build SunamoStringSubstring
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore SunamoStringSubstring/SunamoStringSubstring.csproj

    - name: Build
      run: dotnet build SunamoStringSubstring/SunamoStringSubstring.csproj --configuration Release --no-restore

  test:
    name: Test SunamoStringSubstring.Tests
    runs-on: ${{ matrix.os }}
    needs: build

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore SunamoStringSubstring.Tests/SunamoStringSubstring.Tests.csproj

    - name: Build tests
      run: dotnet build SunamoStringSubstring.Tests/SunamoStringSubstring.Tests.csproj --configuration Release --no-restore

    - name: Run tests
      run: dotnet test SunamoStringSubstring.Tests/SunamoStringSubstring.Tests.csproj --configuration Release --no-build --verbosity normal
      continue-on-error: true
